name: surayweb
description: "Pagina Web Suray"
publish_to: 'Suray'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.13.0
  cloud_firestore: ^4.9.0
  http: ^1.1.0
  intl: ^0.19.0
  universal_html: ^2.2.4  # Para compatibilidad web/móvil
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png
    - assets/ruta_240.png
    - assets/home_panels/aysen.png
    - assets/home_panels/coyhaique.jpg
    - assets/home_panels/tunel.png
    - assets/home_panels/buses.png
    - assets/home_panels/terminal_coy.png
    - assets/home_panels/puente_aysen.png
    - assets/bg/background_route.png
    - assets/logocircle.png
    - assets/insta_icon.png
    - assets/icons/bus_reloj.png
    - assets/icons/calendario_reloj.png
  fonts:
    - family: Hemiheads
    - family: Hemiheads
      fonts:
        - asset: assets/fonts/Hemiheads.otf